version: '3.8'

services:
  frontend:
    build:
      context: ./front-end-3d
      dockerfile: Dockerfile
    ports:
      - "6969:80"
    networks:
      - app-network

  backend:
    build:
      context: ./backend-repo
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
